#!/bin/bash
set -e

echo "=========================================="
echo "Deploying Life Metrics"
echo "=========================================="

REPO_DIR="/opt/metrics-repo"
APP_DIR="/opt/metrics"
DOMAIN="metrics.ltran.co"
EMAIL="linode@ltran.co"

# $APP_DIR and /opt/metrics-repo are created once by root and chowned to the
# deploy user -- its sudoers allowlist has no mkdir, and /opt is root-owned.
# Secrets are placed by hand once; never committed, never touched by CI.
if [ ! -f $APP_DIR/.env ]; then
    echo "ERROR: $APP_DIR/.env is missing. As root, one time:"
    echo "  mkdir -p $APP_DIR /opt/metrics-repo"
    echo "  chown deploy:deploy $APP_DIR /opt/metrics-repo"
    echo "  printf 'INGEST_TOKEN=%s\\n' \"\$(openssl rand -hex 24)\" > $APP_DIR/.env"
    echo "  chown deploy:deploy $APP_DIR/.env && chmod 600 $APP_DIR/.env"
    exit 1
fi

if [ ! -f /etc/nginx/.htpasswd-metrics ]; then
    echo "ERROR: /etc/nginx/.htpasswd-metrics is missing (basic auth for the read API)."
    echo "  sudo htpasswd -bc /etc/nginx/.htpasswd-metrics grafana '<password>'"
    exit 1
fi

# No cert check here, deliberately. /etc/letsencrypt/live is root-only, so any `[ -f ]` test
# against it is always false for the deploy user -- which is the bug that used to make this
# script run `certbot --nginx` on *every* deploy. That was load-bearing by accident: certbot
# re-added the 443 block that the cp below had just deleted from nginx.conf. The vhost is
# declared in the repo now, so certbot is out of the loop entirely.
#
# `sudo nginx -t` below runs as root and fails loudly if the cert is missing, which is the
# right check. To bootstrap a fresh box, get the cert first with a temporary 80-only vhost:
#   sudo certbot certonly --nginx -d metrics.ltran.co

# The read API accepts either basic auth (Grafana) or the ingest bearer token (apps that
# already hold it). nginx can't check a bearer itself, so a map turns a matching
# Authorization header into the realm "off", which disables auth_basic for that request.
#
# Generated here rather than placed by hand so the token lives only in $APP_DIR/.env --
# rotating it means editing .env and redeploying, with nothing to keep in sync. The file is
# not in the repo because it contains the secret.
echo "Generating read-API bearer map..."
# `|| true` so a missing key produces the message below rather than dying on set -e.
INGEST_TOKEN=$(grep -E '^INGEST_TOKEN=' $APP_DIR/.env | head -1 | cut -d= -f2- | tr -d "\"' \r\n" || true)
if [ -z "$INGEST_TOKEN" ]; then
    echo "ERROR: INGEST_TOKEN is missing or empty in $APP_DIR/.env"
    exit 1
fi
TOKEN_CONF=$(mktemp)
chmod 600 $TOKEN_CONF
cat > $TOKEN_CONF <<EOF
# Generated by deploy.sh from $APP_DIR/.env -- do not edit by hand.
#
# The bucket size is not optional: a map key is "Bearer " plus the token, and the default
# bucket of 64 bytes can't hold that. nginx fails with "could not build map_hash" and the
# whole config refuses to load -- which took production down once already.
map_hash_bucket_size 128;

map \$http_authorization \$metrics_auth {
    default                "metrics";
    "Bearer $INGEST_TOKEN" "off";
}
EOF
sudo cp $TOKEN_CONF /etc/nginx/conf.d/metrics-token.conf
rm -f $TOKEN_CONF
unset INGEST_TOKEN

echo "Deploying nginx config..."
sudo cp $REPO_DIR/deploy/nginx.conf /etc/nginx/sites-available/metrics
sudo ln -sf /etc/nginx/sites-available/metrics /etc/nginx/sites-enabled/

# Deliberately no `certbot --nginx` here. That flag rewrites the vhost to add its own 443
# block, which this file already declares -- and the two fought: the cp above would delete
# certbot's block, leaving the site to fall through to gold's 443 vhost on the next reload.
# The cert is a precondition (checked at the top); certbot's systemd timer renews it in place
# and our config reads the same paths, so renewal needs no config change.

echo "Reloading nginx..."
sudo nginx -t
sudo systemctl reload nginx

echo "Deploying application..."
cp $REPO_DIR/deploy/docker-compose.prod.yml $APP_DIR/docker-compose.yml

cd $APP_DIR
export DOCKER_IMAGE=${DOCKER_IMAGE:-ghcr.io/$GITHUB_REPO:latest}

# No `down` -- compose recreates only what changed, so VictoriaMetrics keeps
# running and there's no gap in the series.
docker compose pull
docker compose up -d

echo "Waiting for shim..."
for i in $(seq 1 15); do
    if curl -fsS localhost:8081/healthz >/dev/null 2>&1; then
        echo "Shim healthy"
        break
    fi
    [ "$i" = 15 ] && { echo "ERROR: shim did not come up"; docker compose logs --tail=50 shim; exit 1; }
    sleep 2
done

echo "=========================================="
echo "Deployment complete!"
echo "=========================================="
docker compose ps
